apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: dapr-state-store
  labels:
    app: dapr-infrastructure
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: my-redis-master.redis:6379
    - name: enableTLS
      value: "false"
    - name: actorStateStore
      value: "true"