apiVersion: apps/v1
kind: Deployment
metadata:
  name: orleans-sut
  labels:
    app: orleans-sut
spec:
  replicas: 3
  selector:
    matchLabels:
      app: orleans-sut
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'false'
      labels:
        app: orleans-sut
        orleans/serviceId: actor-benchmark
        orleans/clusterId: actor-benchmark
    spec:
      containers:
        - name: main
          image: abimgregistry.azurecr.io/orleans-sut:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 11111
            - containerPort: 30000
            - containerPort: 8001
          env:
            - name: Orleans__ClusteringStorage
              value: _storage_connection_string_
            - name: SeqUrl
              value: http://my-seq.seq:5341
            - name: ORLEANS_SERVICE_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/serviceId']
            - name: ORLEANS_CLUSTER_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['orleans/clusterId']
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DOTNET_SHUTDOWNTIMEOUTSECONDS
              value: "120"
      terminationGracePeriodSeconds: 180
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: test-role
                    operator: In
                    values:
                      - sut
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - orleans-sut
            