apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-runner
  labels:
    app: test-runner
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-runner
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        dapr.io/enabled: "true"
        dapr.io/app-id: actor-benchmark
        dapr.io/app-port: "5000"
        dapr.io/config: actor-benchmark-config
      labels:
        app: test-runner
    spec:
      containers:
        - name: main
          image: abimgregistry.azurecr.io/test-runner:latest
          imagePullPolicy: Always
          env:
            - name: ActorFramework
              value: Dapr
            - name: Bus__ServiceBusConnectionString
              value: _service_bus_connection_string_
            - name: SeqUrl
              value: http://my-seq.seq:5341
      terminationGracePeriodSeconds: 180
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: test-role
                    operator: In
                    values:
                      - runner
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - test-runner
            