apiVersion: v1
kind: ServiceAccount
metadata:
  name: proto-actor-sut
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: proto-actor-sut-role
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: proto-actor-sut-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: proto-actor-sut-role
subjects:
  - kind: ServiceAccount
    name: proto-actor-sut
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proto-actor-sut
  labels:
    app: proto-actor-sut
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proto-actor-sut
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'false'
      labels:
        app: proto-actor-sut
    spec:
      serviceAccountName: proto-actor-sut
      containers:
        - name: main
          image: abimgregistry.azurecr.io/proto-actor-sut:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 12121
          env:
            - name: SeqUrl
              value: http://my-seq.seq:5341
            - name: ProtoActor__ClusterName
              value: actor-benchmark
            - name: ProtoActor__AdvertisedHost
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP            
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: test-role
                    operator: In
                    values:
                      - sut
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - topologyKey: "kubernetes.io/hostname"
              labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - proto-actor-sut
            